myjob:
  tags:
    - cvmfs

  script:
    - ls /cvmfs/cms.cern.ch/
    - source /cvmfs/cms.cern.ch/cmsset_default.sh
    - export SCRAM_ARCH=slc6_amd64_gcc530
    - CMSSW_VERSION=CMSSW_8_0_24_patch1
    - eval `cmsrel $CMSSW_VERSION`
    - cd $CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`