myjob:
  variables:
    SSH_SERVER_HOSTKEYS: lxplus ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAxDFr+wqtWq0sDCGO2LfsMKVwmhsdXC9TYCVq6HoEBEOXFUgc/3Kf2NooJTgHRQ9h7ZEhx8vdZgoy2+XTwJvqYzx9epIC/gC/ts2z47TvK+FAAkpci5V/5zc9pu8fEYCEwrP+FgF7d3k2ivmZ95Mi/Hhmd9xzxAdps6bpJN19EA0=
  tags:
    - cvmfs
  before_script:
    # taken from https://gitlab.cern.ch/gitlabci-examples/kinit_example
    - mkdir -p ~/.ssh
    # validate lxplus's SSH key
    - 'echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
    # tell SSH to forward Kerberos credentials so lxplus can access AFS/EOS on behalf of the user
    - 'echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\n" > ~/.ssh/config'
  script:
    # simple check to make sure even the basics are there
    - which git
    # get kerberos ticket to access AFS, EOS etc
    - echo "${KRB_PASSWORD}" | kinit -f ${KRB_USERNAME}@CERN.CH
    - klist
    # Now the main action
    - source run.sh