before_script:
  - yum install -y sudo
  - sudo yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
  - sudo yum update -y && sudo yum install -y cvmfs cvmfs-config-default


myjob:
  # tags:
  #   - cvmfs

  script:
    # simple check to make sure even the basics are there
    - which git
    # Now the main action
    - source run.sh