before_script:
  - yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
  - yum update -y && yum install -y cvmfs cvmfs-config-default cvmfs-auto-setup

myjob:
  tags:
    - cvmfs

  script:
    # simple check to make sure even the basics are there
    - which git
    # Now the main action
    - source run.sh