# before_script:
#   - yum install -y sudo
#   - sudo yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
#   - sudo yum update -y && sudo yum install -y cvmfs cvmfs-config-default

# image: hepsw/cvmfs-cms

# before_script:
  # - rpm --rebuilddb && yum install -y svn git glibc gcc


myjob:
  tags:
    - cvmfs
  cache:
    paths:
    - cmssw.git
  script:
    # simple check to make sure even the basics are there
    - which git
    # Now the main action
    - source run.sh