image: gitlab-registry.cern.ch/ci-tools/ci-worker:slc6

# before_script:
#   - yum install -y sudo
  # - ls -l /
  # - mkdir -p /cvmfs/cms.cern.ch
  # - service autofs stop
  # - chkconfig autofs off
  # - echo "cms.cern.ch /cvmfs/cms.cern.ch cvmfs defaults 0 0" >> /etc/fstab
  # - yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
  # - yum install -y cvmfs cvmfs-config-default


myjob:
  tags:
    - cvmfs
  script:
    # simple check to make sure even the basics are there
    - which git
    # Now the main action
    - source run.sh