sudo: required

language: c++

services:
  - docker

# If you want to build it in the CI:

before_install:
  - docker version
  - docker pull cern/slc6-base
  # - docker pull hepsw/cvmfs-cms

# install:

# script:
#   - sudo docker exec --privileged -t myCI /bin/bash -c "source run.sh"

script:
  # To use the pre-built image:
  # - sudo docker run --privileged --name myCI -t -v $PWD:/app -d raggleton/mycmssw:test /bin/bash
  # ad hoc one:
  - sudo docker build -t mycmssw -f Dockerfile .
  - sudo docker run --privileged --name myCI -t -v $PWD:/app -d mycmssw /bin/bash
  - sudo docker exec --privileged -t myCI /bin/bash -c "source run.sh"

notifications:
  email:
    on_failure: never
#     on_success: never
