sudo: required

language: c++

services:
  - docker

# If you want to build it in the CI:

before_install:
  - docker version
  - docker pull hepsw/cvmfs-cms

install:
  - sudo docker build -t mycmssw -f Dockerfile .
  
script:
  # To use the pre-built image:
  # - sudo docker run --privileged --name myCI -ti -v $PWD:/app raggleton/mycmssw:test
  # ad hoc one:
  - sudo docker run --privileged --name myCI -ti -v $PWD:/app mycmssw

notifications:
  email:
    on_failure: always
    on_success: never
