sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get install lsb-release
  - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo apt-get update
  - sudo apt-get install cvmfs cvmfs-config-default
  - rm -f cvmfs-release-latest_all.deb
  - sudo cvmfs_config setup
  - sudo mkdir -p /etc/cvmfs/ 
  - sudo mv default.local /etc/cvmfs/default.local
  - sudo service autofs restart
  - sudo cvmfs_config setup
  - sudo cvmfs_config chksetup


install: true

script:
  - ./run.sh