sudo: required

language: python

services:
  - docker

before_install:
  - docker pull cern/slc6-base

install:
  - sudo docker build -t mycmssw -f Dockerfile .

script:
  - sudo docker run --privileged -t mycmssw
