sudo: required

language: python

services:
  - docker

before_install:
  - docker pull cern/slc6-base

install:
  - docker build -t mycmssw -f Dockerfile .

script:
  - docker run --privileged mycmssw